AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Lint/EmptyClass:
  AllowComments: true

Style/GlobalVars:
  AllowedVariables:
    - $LAST_PUT_LINE

Style/OptionalBooleanParameter:
  AllowedMethods:
    - consent?
    - dissent?

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/*.rb'
